[package]
name = "spi_sd_card"
version = "0.1.0"
edition = "2024"

[dependencies]
bitfield = "0.19.4"
bitflags = "2.10.0"
crc = "3.4.0"
defmt = "1.0.1"
embassy-time = "0.5.0"
embedded-hal = "1.0.0"
embedded-hal-async = "1.0.0"
